apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
namespace: janus-idp
components:
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/large
- ../../../../components/project-admin-rolebindings/janus-idp
